excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://AliKeremKaralar.github.io
title: AliKeremKaralar
tagline: A log of everyday life
description: My awesome new site
paginate: 5